# Generated by Django 3.2.13 on 2023-07-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='home.category')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_subcategories', to='home.subcategory')),
            ],
            options={
                'unique_together': {('name', 'subcategory')},
            },
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='home.department')),
            ],
            options={
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='subdepartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='home.subdepartment'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'subdepartment')},
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=300, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.department')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subcategory')),
                ('subdepartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subdepartment')),
                ('subsubcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subsubcategory')),
            ],
            options={
                'unique_together': {('year', 'subdepartment'), ('year', 'subcategory'), ('year', 'department'), ('year', 'subsubcategory'), ('year', 'category')},
            },
        ),
    ]
